apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: nginx-daemon-set
spec:
  template:
    metadata:
      annotations:
        "scheduler.alpha.kubernetes.io/name": poseidon
      labels:
        name: nginx-daemon-set
    spec:
      containers:
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          ports:
             - containerPort: 80
