apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      annotations:
        "scheduler.alpha.kubernetes.io/name": poseidon
      name: nginx-replica-set
      labels:
        tier: frontend
        scheduler: poseidon
    spec:
      containers:
        - name: nginx
          image: "nginx:1.11.1-alpine"
          ports:
             - containerPort: 80
